name: Publish(from GH Release)

on:
  workflow_dispatch:

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Copy from GH to PyPi
    steps:
    - uses: actions/checkout@v3
    - name: Get release info
      id: get_release_info
      run: |
        RELEASE_VERSION=$(sed -n "s/^__version__.*\"\(.*\)\"$/\\1/p" ./pillow_heif/_version.py)
        echo "::set-output name=tag::v${RELEASE_VERSION}"

    - name: Download Release Assets
      id: download_release_assets
      uses: i3h/download-release-asset@v1
      with:
        owner: ${{github.repository_owner}}
        repo: ${{ github.event.repository.name }}
        tag: ${{ steps.get_release_info.outputs.tag }}
        file: '/.*pillow_heif.*/'
        path: wheelhouse/

    - name: Publish wheels to PyPI
      run: |
          python3 -m pip install twine
          ls -la wheelhouse/
          twine upload --verbose --skip-existing wheelhouse/*.whl
          twine upload --verbose wheelhouse/*tar.gz
