name: Build from src

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Analysis & Coverage]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: ${{ matrix.distro }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ubuntu:focal", "ubuntu:jammy"]
        arch: ["linux/amd64"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up qemu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build pillow_heif
        run: |
          docker buildx build --platform ${{ matrix.arch }} --build-arg DISTRO="${{ matrix.distro }}" -f docker/from_src.Dockerfile .
